- .github/workflows/crystal.yml
- .github/workflows/release.yml
- .gitignore
- Makefile
- shard.lock
- src/coverage_reporter/cli/cmd.cr
> ci: create a release on tag push

- spec/coverage_reporter/parsers/cobertura_parser_spec.cr
- spec/coverage_reporter/parsers/lcov_parser_spec.cr
- spec/coverage_reporter/parsers/simplecov_parser_spec.cr
- spec/fixtures/cobertura/cobertura.xml
- src/coverage_reporter/api/jobs.cr
- src/coverage_reporter/file_report.cr
- src/coverage_reporter/parser.cr
- src/coverage_reporter/parsers/cobertura_parser.cr
- src/coverage_reporter/parsers/lcov_parser.cr
> feat: add cobertura coverage parser

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/need_help.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
> chore: add issue and PR templates

- README.md
- doc/configuration.md
- spec/coverage_reporter/api/webhook_spec.cr
- spec/coverage_reporter_spec.cr
- src/coverage_reporter.cr
- src/coverage_reporter/api/webhook.cr
- src/coverage_reporter/cli/cmd.cr
Add `carryforward` option for parallel flow
> feat: add carryforward option

- .github/workflows/release.yml
> ci: add Windows build and checksums

- .ameba.yml
- README.md
- spec/coverage_reporter/parser_spec.cr
- spec/coverage_reporter/parsers/gcov_parser_spec.cr
- spec/coverage_reporter/parsers/lcov_parser_spec.cr
- spec/fixtures/gcov/.gitignore
- spec/fixtures/gcov/Makefile
- spec/fixtures/gcov/main.c
- spec/fixtures/gcov/main.c.gcov
- src/coverage_reporter/file_report.cr
- src/coverage_reporter/parser.cr
- src/coverage_reporter/parsers/base_parser.cr
- src/coverage_reporter/parsers/gcov_parser.cr
- src/coverage_reporter/parsers/lcov_parser.cr
- src/coverage_reporter/parsers/simplecov_parser.cr
> feat: add gcov format support

- spec/fixtures/test.lcov
- src/coverage_reporter/parsers/lcov_parser.cr
Closes https://github.com/coverallsapp/github-action/issues/155
> fix: skip non-existing files for LCOV

- README.md
- spec/coverage_reporter/parser_spec.cr
- spec/coverage_reporter/parsers/jacoco_parser_spec.cr
- spec/fixtures/jacoco/jacoco-report.xml
- src/coverage_reporter/parser.cr
- src/coverage_reporter/parsers/jacoco_parser.cr
> feat: add jacoco parser

- .coveralls.yml
- .github/workflows/ci.yml
- .github/workflows/crystal.yml
- .gitignore
- README.md
- shard.lock
- shard.yml
- spec/coverage_reporter/parser_spec.cr
- src/coverage_reporter/parsers/cobertura_parser.cr
> chore: add coverage

- spec/coverage_reporter/config_spec.cr
- src/coverage_reporter/ci/github.cr
> feat: add PR number for Github

- README.md
- spec/coverage_reporter/parsers/cobertura_parser_spec.cr
- spec/coverage_reporter/parsers/jacoco_parser_spec.cr
- src/coverage_reporter/parsers/cobertura_parser.cr
- src/coverage_reporter/parsers/jacoco_parser.cr
> fix: use stricter xml matching

- README.md
- doc/configuration.md
- doc/examples/circleci-orb.yml
- doc/examples/circleci.yml
- doc/examples/github-actions-default.yml
- doc/examples/github-actions.yml
- lefthook.yml
Update docs to make them more intuitive.
> docs: update readme

- README.md
- doc/configuration.md
- spec/coverage_reporter/config_spec.cr
- spec/coverage_reporter/reporter_spec.cr
- src/coverage_reporter/cli/cmd.cr
- src/coverage_reporter/config.cr
- src/coverage_reporter/reporter.cr
- Add `compare_ref` option
- Add `compare_sha` option
> feat: add compare_ref and compare_sha options

- spec/coverage_reporter/api/jobs_spec.cr
- spec/coverage_reporter/api/webhook_spec.cr
- src/coverage_reporter/api.cr
- src/coverage_reporter/api/jobs.cr
- src/coverage_reporter/api/webhook.cr
- src/coverage_reporter/file_report.cr
- src/coverage_reporter/parser.cr
- src/coverage_reporter/parsers/cobertura_parser.cr
- src/coverage_reporter/parsers/coveragepy_parser.cr
- src/coverage_reporter/parsers/gcov_parser.cr
- src/coverage_reporter/parsers/golang_parser.cr
- src/coverage_reporter/parsers/jacoco_parser.cr
- src/coverage_reporter/parsers/lcov_parser.cr
- src/coverage_reporter/parsers/simplecov_parser.cr
- src/coverage_reporter/source_files.cr
Add some info in headers about coverage reporter context.
> feat: add info headers

- .github/workflows/build.yml
- Dockerfile
- Makefile
> chore: bump Crystal to 1.7.3

- doc/configuration.md
- src/coverage_reporter/config.cr
- src/coverage_reporter/reporter.cr
- src/coverage_reporter/yaml_config.cr
Add `carryforward` option to YAML config. Also add a note about `all` value.
> feat: add carryforward option to config

- spec/coverage_reporter/cli/cmd_spec.cr
- spec/coverage_reporter/config_spec.cr
- src/coverage_reporter/ci/github.cr
- src/coverage_reporter/ci/options.cr
- src/coverage_reporter/cli/cmd.cr
Pass GITHUB_RUN_ATTEMPT env value as `run_attempt`
> feat: pass github run attempt

- .github/workflows/build.yml
- .github/workflows/ci.yml
- Makefile
- shard.lock
- shard.yml
- src/coverage_reporter/parser.cr
> fix: new Crystal version and Coveralls parser

- README.md
- spec/coverage_reporter/cli/cmd_spec.cr
- src/coverage_reporter/cli/cmd.cr
Add `--no-fail` option to always return 0 even if upload failed
> feat(cli): add --no--fail option

- src/coverage_reporter/parsers/lcov_parser.cr
Optimize regexps for LCOV parser
> fix: optimize lcov parser

- README.md
> Mention Clover XML in README

- .github/workflows/build.yml
Add debugging steps to `release` job in build workflow.
> Add debugging steps to release job in build workflow.

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/test-binaries.yml
- .github/workflows/test-trigger-workflow.yml
Fix issue with `test-binaries` workflow not firing after `build` workflow completes
> Fix issue with `test-binaries` workflow not firing after `build` workflow completes
