- spec/coverage_reporter/config_spec.cr
- src/coverage_reporter/ci/github.cr
- src/coverage_reporter/ci/gitlab.cr
- src/coverage_reporter/parsers/simplecov_parser.cr
> fix: Github Actions specific fixes

- spec/coverage_reporter/config_spec.cr
- src/coverage_reporter/api/webhook.cr
- src/coverage_reporter/ci/github.cr
- src/coverage_reporter/ci/options.cr
- src/coverage_reporter/config.cr
Add more parameters for simplicity (in coveralls backend) and verbosity.
> feat: pass repo_name in Github Actions

- spec/coverage_reporter/config_spec.cr
- src/coverage_reporter/ci/github.cr
Summary:
- Use GITHUB_HEAD_REF (is set for PRs) and GITHUB_REF_NAME (as fallback)
> fix: correct branch name for Github Actions

- README.md
- doc/configuration.md
- doc/development.md
- src/coverage_reporter/api/jobs.cr
- src/coverage_reporter/config.cr
- src/coverage_reporter/parsers/base_parser.cr
> docs: update README instructions

- src/coverage_reporter/ci/github.cr
- src/coverage_reporter/cli/cmd.cr
This change will allow for easier usage within Github Actions where we can have empty ENVs and should ignore them.
> fix: skip empty ENVs to prevent empty configuration

- spec/coverage_reporter/parser_spec.cr
- spec/coverage_reporter/reporter_spec.cr
- src/coverage_reporter/cli/cmd.cr
- src/coverage_reporter/parser.cr
- src/coverage_reporter/parsers/base_parser.cr
- src/coverage_reporter/parsers/coveragepy_parser.cr
- src/coverage_reporter/reporter.cr
Closes https://github.com/coverallsapp/coverage-reporter/issues/36
Add `--format` option which allows to force coverage format for either specified `--filename` or all files found automatically.
```
--format=FORMAT   Force coverage file format, supported formats: lcov, simplecov, cobertura, jacoco, gcov, golang, python
```
> feat: add an option to force coverage format

- spec/coverage_reporter/config_spec.cr
- src/coverage_reporter/ci/jenkins.cr
CI options for Jenkins were changed with recent release, but this led to issues. Returning `service_number = $BUILD_NUMBER`
> fix: jenkins ci

- src/coverage_reporter/parsers/base_parser.cr
- src/coverage_reporter/parsers/cobertura_parser.cr
- src/coverage_reporter/parsers/coveragepy_parser.cr
- src/coverage_reporter/parsers/gcov_parser.cr
- src/coverage_reporter/parsers/golang_parser.cr
- src/coverage_reporter/parsers/jacoco_parser.cr
- src/coverage_reporter/parsers/lcov_parser.cr
- src/coverage_reporter/parsers/simplecov_parser.cr
Make sure all parsers calculate `source_digest` for files (if files are reachable)
> chore: add source_digest to all parsers

- spec/fixtures/cobertura/cobertura.xml
- src/coverage_reporter/cli/cmd.cr
- src/coverage_reporter/parser.cr
- src/coverage_reporter/parsers/cobertura_parser.cr
Cobertura can contain empty results. In this case we shouldn't raise an error
> fix: allow empty coverage for cobertura

- spec/coverage_reporter/parsers/jacoco_parser_spec.cr
- spec/fixtures/jacoco/jacoco-report.xml
- src/coverage_reporter/parsers/golang_parser.cr
- src/coverage_reporter/parsers/jacoco_parser.cr
Closes https://github.com/coverallsapp/github-action/issues/160
Closes https://github.com/coverallsapp/coverage-reporter/issues/45
Use `max?` instead of `max`
> fix: jacoco parsing

- spec/coverage_reporter/api/jobs_spec.cr
- spec/coverage_reporter/api/webhook_spec.cr
- src/coverage_reporter/api.cr
- src/coverage_reporter/api/jobs.cr
- src/coverage_reporter/api/webhook.cr
- src/coverage_reporter/config.cr
- src/coverage_reporter/yaml_config.cr
> feat: allow specifying endpoint in yaml config

- spec/coverage_reporter/parsers/golang_parser_spec.cr
- spec/fixtures/golang/coverage-dashes.out
- src/coverage_reporter/parsers/golang_parser.cr
Extend regexp for golang coverage to allow dashes in repo names
> fix: improve golang detector regexp

- src/coverage_reporter/cli/cmd.cr
Closes https://github.com/coverallsapp/orb/pull/28
Treat `0` as falsey value of `COVERALLS_PARALLEL`
> fix: treat 0 as false value

- spec/coverage_reporter/config_spec.cr
- src/coverage_reporter/ci/gitlab.cr
Change ENV options for Gitlab CI:
- Remove `service_job_number` in case of too big numbers that can't be processed
- Add `service_number` to reference pipeline IID
- Change `service_build_url` to have pipeline URL
- Add merge request IID
> fix: options for Gitlab CI

- .ameba.yml
- README.md
- doc/configuration.md
- spec/coverage_reporter/cli/cmd_spec.cr
- spec/coverage_reporter/reporter_spec.cr
- src/coverage_reporter/base_exception.cr
- src/coverage_reporter/cli/cmd.cr
- src/coverage_reporter/parser.cr
- src/coverage_reporter/reporter.cr
Add an option to support empty coverage files without returning an error code.
> feat: add allow empty coverage flag

- spec/coverage_reporter/config_spec.cr
- src/coverage_reporter/ci/semaphore.cr
and add additional options from available variables
Per [semaphore docs](https://docs.semaphoreci.com/ci-cd-environment/environment-variables/), use the correct ENV variable names.
This partially addresses #55, in that the reporter should now read the correct environment variables on Semaphore, but does not address `--service-job-id` being ignored when `--done` is present.
The only thing I'm not sure about here is the `service_build_url` and `service_job_url` semantics mapping. On semaphore, the "job" is the individual process and the "workflow" is the entire build.
> fix(semaphore): correct ENV variables

- src/coverage_reporter/file_report.cr
- src/coverage_reporter/parsers/coveragepy_parser.cr
- src/coverage_reporter/parsers/gcov_parser.cr
- src/coverage_reporter/parsers/lcov_parser.cr
- src/coverage_reporter/parsers/simplecov_parser.cr
Replace `name.sub(Dir.current, "")` to `name.sub(Regex.new("^#{Dir.current}"), "")` in order to prevent accidental change in real paths.
> fix: substitute current dir only from the path start

- spec/coverage_reporter/cli/cmd_spec.cr
- src/coverage_reporter/file_report.cr
- src/coverage_reporter/reporter.cr
Relates to https://github.com/coverallsapp/github-action/issues/169
Tries replacing current directory in the `name` with both variants: slashes and backslashes (important for Windows)
> fix: lcov absolute paths in Windows

- .github/workflows/build.yml
- .github/workflows/ci.yml
- Dockerfile
- Makefile
- spec/coverage_reporter/cli/cmd_spec.cr
- src/coverage_reporter/parsers/golang_parser.cr
Closes https://github.com/coverallsapp/coverage-reporter/issues/65
In Crystal 1.8 they use pcre2 ([PR](https://github.com/crystal-lang/crystal/pull/13084)), and it raises an exception when parsing non UTF-8 text. It's hard to find out what exactly was wrong (as said [here](https://dev.to/seesethcode/crystal-pcre2-upgrade-guide-58eo), PCRE2 devs don't remember that :thinking:), so let's leave it for the later work. This PR downgrades Crystal version where everything worked just fine.
> fix: use Crystal 1.7.3

- .github/workflows/build.yml
- .github/workflows/ci.yml
- Makefile
- shard.yml
> chore: use just Crystal 1.8 version

- src/coverage_reporter/parsers/simplecov_parser.cr
Introduce more simple way for parsing data.
> chore: refactor aliases usage

- spec/coverage_reporter/parsers/simplecov_parser_spec.cr
- spec/fixtures/simplecov/with-only-lines.resultset.json
- src/coverage_reporter/parsers/simplecov_parser.cr
Closes https://github.com/coverallsapp/coverage-reporter/issues/76
- Make `branches` nilable
> fix: allow no branches in simplecov format

- README.md
- spec/coverage_reporter/parsers/coveralls_parser_spec.cr
- spec/fixtures/coveralls/coveralls.json
- src/coverage_reporter/parsers/cobertura_parser.cr
- src/coverage_reporter/parsers/coveralls_parser.cr
> feat: support coveralls format

- spec/coverage_reporter/api/jobs_spec.cr
- src/coverage_reporter/api/jobs.cr
Closes https://github.com/coverallsapp/coverage-reporter/issues/80
We were passing all files in a header, so its size was about 20Kb, which is not acceptable.
> fix: don't send all files in header

- .github/workflows/build.yml
- .github/workflows/ci.yml
- doc/development.md
- spec/coverage_reporter/parsers/jacoco_parser_spec.cr
- spec/fixtures/jacoco/jacoco-report-multiple-packages.xml
- src/coverage_reporter/file_report.cr
- src/coverage_reporter/parsers/base_parser.cr
- src/coverage_reporter/parsers/cobertura_parser.cr
- src/coverage_reporter/parsers/coveragepy_parser.cr
- src/coverage_reporter/parsers/coveralls_parser.cr
- src/coverage_reporter/parsers/gcov_parser.cr
- src/coverage_reporter/parsers/golang_parser.cr
- src/coverage_reporter/parsers/jacoco_parser.cr
- src/coverage_reporter/parsers/lcov_parser.cr
- src/coverage_reporter/parsers/simplecov_parser.cr
Move `base_path` applying from parser to FileReport itself. Also support globs for base_path, so it can search for files in accessible dirs and find the right dir.
NOTE: Name collision issue can still take place. Make sure you don't have same filepaths in different base_paths.
> feat: support globs for base path

- README.md
- spec/coverage_reporter/cli/cmd_spec.cr
- spec/coverage_reporter/parser_spec.cr
- spec/coverage_reporter/reporter_spec.cr
- src/coverage_reporter/api/jobs.cr
- src/coverage_reporter/cli/cmd.cr
- src/coverage_reporter/parser.cr
- src/coverage_reporter/parsers/base_parser.cr
- src/coverage_reporter/reporter.cr
> feat: add explicit commands

- .ameba.yml
- shard.lock
- shard.yml
- spec/coverage_reporter/api/jobs_spec.cr
- spec/coverage_reporter/api/webhook_spec.cr
- spec/coverage_reporter/cli/cmd_spec.cr
- spec/spec_helper.cr
- spec/support/reporter_mock.cr
- src/cli.cr
- src/coverage_reporter/api.cr
- src/coverage_reporter/api/jobs.cr
- src/coverage_reporter/api/webhook.cr
- src/coverage_reporter/cli/cmd.cr
- src/coverage_reporter/log.cr
- src/coverage_reporter/parsers/simplecov_parser.cr
- src/coverage_reporter/reporter.cr
> feat: gzip payloads

- spec/coverage_reporter/api/webhook_spec.cr
- spec/coverage_reporter/cli/cmd_spec.cr
- src/coverage_reporter/api/webhook.cr
- src/coverage_reporter/cli/cmd.cr
- src/coverage_reporter/reporter.cr
This PR adds more info to webhook request - git information. This allows to create a new build (with all required information) with previous jobs carry-forwarded via the following command:
```bash
coveralls done --build-number 123 --carryforward all
```
NOTE: build-number must be different from the previously reported build. Otherwise no new builds will be created.
> feat: pass more params on webhook request

- README.md
From https://github.com/coverallsapp/coverage-reporter/pull/102#discussion_r1379146124
I thought it was the program's name.
Sorry.
props. @jrfnl
> Fix clover's format name in README

- .github/workflows/build.yml
This fixes the windows build by dynamically retrieving the path to `dumpbin.exe`.
> Dynamically retrieve the path to dumpbin.exe for windows build

- README.md
Add instructions for how to trigger final step in Homebrew release in README.
> Update release instructions with Homebrew release info

- spec/coverage_reporter/parser_spec.cr
- spec/coverage_reporter/parsers/gcov_parser_spec.cr
- spec/coverage_reporter/parsers/lcov_parser_spec.cr
- spec/coverage_reporter/parsers/simplecov_parser_spec.cr
- src/coverage_reporter/parser.cr
- src/coverage_reporter/parsers/gcov_parser.cr
- src/coverage_reporter/parsers/lcov_parser.cr
- src/coverage_reporter/parsers/simplecov_parser.cr
Problem
--------
All files are now run through a parser's `matches?`
method, which is causing issues for the lcov,
gcov, and simplecov parsers since the
`matches?` method checks that files have a
particular file extension. This is causing failures
when users pass a custom file.
Solution
--------
The lcov, gcov, and simplecov parsers were moved
to the last in the array of parsers, since they are
the only parsers which do not check actual
file contents to see if a file is of the correct 
format. In order to ensure that these three
parsers will not erroneously match on files of
the other two types, we modify the `matches?`
method to return false if file extensions of the
other two parsers are matched. 
If a user is passing a custom gcov, simplecov, or
lcov parser with a non-standard file …
> Remove restriction on file extension for some parsers

- .github/workflows/build.yml
- .github/workflows/ci.yml
- Makefile
- Updates **Crystal lang version** from `1.9.1` to `1.13.1` (latest stable version).
- **Crystal** `1.13.1` has better support for mutliple architectures including `aarch64`.
-  Our next release of `coverage-reporter` after this one requires support for `aarch64` and will therefore need to cross-compile **two** (**2**) **linux binaries** for: 
1. `x86_64` 
2. `aarch64`.
> Update Crystal Lang version to 1.13.1, the latest stable version.

- Makefile
- Modify Makefile to fix issues with sed handling inputs.
- Prior to changes, `make new_version` was throwing errors like this:
```bash
% make new_version
New version: 0.6.13
Brief description: Update Crystal lang version to 1.13.1
sed -i "s/version:.*/version: $version/" shard.yml
sed: 1: "shard.yml": unterminated substitute pattern
make: *** [new_version] Error 1
```
> Modify Makefile to fix issues with sed handling inputs.

- .github/workflows/build.yml
- Dockerfile
Closes #137 
Add `aarch64` support to `coverage-reporter`.
Update `build.yml` workflow to cross-compile linux binaries for `x86_64` and `aarch64`.
> Update `build.yml` workflow to cross-compile linux binaries for `x86_64` and `aarch64`

- .github/workflows/build.yml
Fix some remaining issues with, and finalize, the `build.yml` workflow.
> Correct the version declaration for the homebrew-bump-formula action.

- .github/workflows/build.yml
> Fix syntax on GitHub CLI call.

- .github/workflows/build.yml
- Dockerfile
- README.md
- src/coverage_reporter.cr
Fix problems with last attempted release:
> Fix problems with latest release

- spec/coverage_reporter/parsers/golang_parser_spec.cr
- spec/fixtures/golang/coverage-one-slash.out
- spec/fixtures/golang/coverage-two-slashes.out
- src/coverage_reporter/parsers/golang_parser.cr
I updated go to go 1.22 and noticed that CI was failing to upload test coverage to coveralls. I discovered that coveralls was detecting the file type as `lcov` when it should have been `golang`. This was because the regex in the golang parser expected three slashes in the file path for each file under test.
I updated the regex to only have one slash be required, while ensuring that existing tests didn't fail. I added two new fixture files and added two new tests to ensure the new behavior works correctly.
> Update golang parser regex

- .github/workflows/build.yml
- Dockerfile
Revert CI/CD changes for cross-compile effort to allow intermediate release.
> Revert CI/CD changes for cross-compile effort to allow intermediate release

- .github/workflows/test-binaries.yml
Closes # (issue(s))
Adds new trigger to workflow that test multi-architecture linux binaries to run after the workflow that builds the binaries completes.
> Trigger test-binaries workflow to run after build workflow completes.

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/test-binaries.yml
Resolving issues with a new workflow, `test-binaries.yml` that attempts to test the latest versions of our multi-arch linux binaries in architecture-specific environments, just after they are built in CI.
> Test Linux Binaries after they're built in CI

- .github/workflows/test-binaries.yml
Resolve issues with workflow, `test-binaries.yml`, that attempts to test the latest versions of our multi-arch linux binaries in architecture-specific environments, just after they are built in CI.
> Test Linux Binaries after they're built in CI (Cont'd)

- .github/workflows/build.yml
Actually, we closed these issues with a **patch** in which we downloaded, changed, and re-uploaded the `coveralls-checksums.txt` file to release `v.0.6.15`, but this fix makes sure the same issue won't occur in future releases:
- #165 
- https://github.com/coverallsapp/github-action/issues/224
- https://github.com/coverallsapp/orb/issues/45
Fixes the statement that creates the `coveralls-checksums.txt` file.
**Reasoning**: These files will be downloaded at the root level for users of each binary, so the checksums need to refer to the files without any paths included.
> Fix statement that creates coveralls-checksums.txt
